# Cấu hình màn hình
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600

# Thông số vật lý
GRAVITY = 0.8
JUMP_FORCE = 15
PLAYER_SPEED = 5.0

# Thông số nhân vật
PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64

# Thông số kẻ thù
ENEMY_SPEED = 2.0
ENEMY_WIDTH = 50
ENEMY_HEIGHT = 50

# Thông số Map
TILE_SIZE = 64
GROUND_DISPLAY_Y = -192
GROUND_Y_AREA_A = 90
